LigaPrvaka/Controllers/IgracisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LigaPrvaka.ModelEF;

namespace LigaPrvaka.Controllers
{
    public class IgracisController : Controller
    {
        private LigaprvakaEntities db = new LigaprvakaEntities();

        // GET: Igracis
        public ActionResult Index()
        {
            var igracis = db.Igracis.Include(i => i.Timovi);
            return View(igracis.ToList());
        }

        public ActionResult IgraciTima(int TimID)
        {
            var igraci = db.Igracis.Where(k => k.FKTimID == TimID);
            return PartialView(igraci.ToList());
        }
        // GET: Igracis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igraci igraci = db.Igracis.Find(id);
            if (igraci == null)
            {
                return HttpNotFound();
            }
            return View(igraci);
        }

        // GET: Igracis/Create
        public ActionResult Create()
        {
            ViewBag.FKTimID = new SelectList(db.Timovis, "PKTimID", "Naziv");
            return View();
        }

        // POST: Igracis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PKIgracID,Ime,FKTimID")] Igraci igraci)
        {
            if (ModelState.IsValid)
            {
                db.Igracis.Add(igraci);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FKTimID = new SelectList(db.Timovis, "PKTimID", "Naziv", igraci.FKTimID);
            return View(igraci);
        }

        // GET: Igracis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igraci igraci = db.Igracis.Find(id);
            if (igraci == null)
            {
                return HttpNotFound();
            }
            ViewBag.FKTimID = new SelectList(db.Timovis, "PKTimID", "Naziv", igraci.FKTimID);
            return View(igraci);
        }

        // POST: Igracis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PKIgracID,Ime,FKTimID")] Igraci igraci)
        {
            if (ModelState.IsValid)
            {
                db.Entry(igraci).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FKTimID = new SelectList(db.Timovis, "PKTimID", "Naziv", igraci.FKTimID);
            return View(igraci);
        }

        // GET: Igracis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igraci igraci = db.Igracis.Find(id);
            if (igraci == null)
            {
                return HttpNotFound();
            }
            return View(igraci);
        }

        // POST: Igracis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Igraci igraci = db.Igracis.Find(id);
            db.Igracis.Remove(igraci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LigaPrvaka/Controllers/UtakmicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LigaPrvaka.ModelEF;

namespace LigaPrvaka.Controllers
{
    public class UtakmicesController : Controller
    {
        private LigaprvakaEntities db = new LigaprvakaEntities();

        // GET: Utakmices
        public ActionResult Index()
        {
            var utakmice = db.Utakmice.Include(u => u.Timovi).Include(u => u.Timovi1);
            return View(utakmice.ToList());
        }

        // GET: Utakmices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utakmouse utakmouse = db.Utakmice.Find(id);
            if (utakmouse == null)
            {
                return HttpNotFound();
            }
            return View(utakmouse);
        }

        // GET: Utakmices/Create
        public ActionResult Create()
        {
            ViewBag.Domaci = new SelectList(db.Timovis, "PKTimID", "Naziv");
            ViewBag.Gosti = new SelectList(db.Timovis, "PKTimID", "Naziv");
            return View();
        }

        // POST: Utakmices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PKUtakmicaID,Domaci,Gosti,Br_golova_d,Br_golova_g")] Utakmouse utakmouse)
        {
            if (ModelState.IsValid)
            {
                db.Utakmice.Add(utakmouse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Domaci = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Domaci);
            ViewBag.Gosti = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Gosti);
            return View(utakmouse);
        }

        // GET: Utakmices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utakmouse utakmouse = db.Utakmice.Find(id);
            if (utakmouse == null)
            {
                return HttpNotFound();
            }
            ViewBag.Domaci = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Domaci);
            ViewBag.Gosti = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Gosti);
            return View(utakmouse);
        }

        // POST: Utakmices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PKUtakmicaID,Domaci,Gosti,Br_golova_d,Br_golova_g")] Utakmouse utakmouse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utakmouse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Domaci = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Domaci);
            ViewBag.Gosti = new SelectList(db.Timovis, "PKTimID", "Naziv", utakmouse.Gosti);
            return View(utakmouse);
        }

        // GET: Utakmices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utakmouse utakmouse = db.Utakmice.Find(id);
            if (utakmouse == null)
            {
                return HttpNotFound();
            }
            return View(utakmouse);
        }

        // POST: Utakmices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utakmouse utakmouse = db.Utakmice.Find(id);
            db.Utakmice.Remove(utakmouse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LigaPrvaka/Views/Utakmices/Create.cshtml
@model LigaPrvaka.ModelEF.Utakmouse

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utakmouse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Domaci, "Domaci", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Domaci", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Domaci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gosti, "Gosti", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gosti", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gosti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Br_golova_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Br_golova_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Br_golova_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Br_golova_g, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Br_golova_g, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Br_golova_g, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LigaPrvaka/Views/Utakmices/Delete.cshtml
@model LigaPrvaka.ModelEF.Utakmouse

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utakmouse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Br_golova_d)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Br_golova_d)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Br_golova_g)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Br_golova_g)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timovi.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timovi.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timovi1.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timovi1.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LigaPrvaka/Views/Utakmices/Details.cshtml
@model LigaPrvaka.ModelEF.Utakmouse

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Utakmice</h4>
    
    @*<dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Domaci:")
            </dt>

            <dd>
                @Html.Action("IgraciTima", "Igracis", new { TimID = Model.Domaci })
            </dd>

            <dt>
                @Html.DisplayName("Gosti:")
            </dt>

            <dd>
                @Html.Action("IgraciTima", "Igracis", new { TimID = Model.Gosti })
            </dd>


        </dl>*@
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Domaci")
            </th>

            <th>
                @Html.DisplayName("Gosti")
            </th>

        </tr>

        <tr>
            <td>
                @Html.DisplayFor(model => model.Br_golova_d)
                @Html.Action("IgraciTima", "Igracis", new { TimID = Model.Domaci })
            </td>
            <td>
                @Html.DisplayFor(model => model.Br_golova_g)
                @Html.Action("IgraciTima", "Igracis", new { TimID = Model.Gosti })
            </td>

        </tr>
    </table>

</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PKUtakmicaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LigaPrvaka/Views/Utakmices/Edit.cshtml
@model LigaPrvaka.ModelEF.Utakmouse

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utakmouse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PKUtakmicaID)

        <div class="form-group">
            @Html.LabelFor(model => model.Domaci, "Domaci", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Domaci", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Domaci, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gosti, "Gosti", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gosti", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gosti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Br_golova_d, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Br_golova_d, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Br_golova_d, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Br_golova_g, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Br_golova_g, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Br_golova_g, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LigaPrvaka/Views/Utakmices/Index.cshtml
@model IEnumerable<LigaPrvaka.ModelEF.Utakmouse>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Domaci")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Br_golova_d)
        </th>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Br_golova_g)

        </th>
        <th>
            @Html.DisplayName("Gosti")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Timovi.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Br_golova_d)
            </td>
            <td>
                @Html.DisplayName(":")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Br_golova_g)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timovi1.Naziv)
            </td>
            <td>               
                @Html.ActionLink("Details", "Details", new { id = item.PKUtakmicaID })              
            </td>
        </tr>
    }

</table>